#!/usr/bin/env python
# vim: ft=python
""" Get tag with fewest commits from given branch

Usage:

    git-closest-tag [commit-ish]

To get closest tag to current HEAD

    git-closest-tag

To get closest tag to origin/master

    git-closest-tag origin/master
"""
# Requires at least Python 2.7
from __future__ import print_function

import sys
from subprocess import check_output


def backtick(cmd):
    """ Get command output as stripped string """
    output = check_output(cmd)
    return output.decode('latin1').strip()


def main():
    # Get commit-ish from passed command arguments, HEAD is default
    try:
        target_ref = sys.argv[1]
    except IndexError:
        target_ref = 'HEAD'
    # SHA1 for target reference
    target_commit = backtick(['git', 'rev-parse', target_ref])
    min_distance = float('inf')
    tag_lines = backtick(['git', 'tag']).split('\n')
    if len(tag_lines) == 0:
        raise RuntimeError("No tags to compare")
    for line in tag_lines:
        tag = line.strip()
        # Check for case where tag and target are the same
        tag_commit = backtick(['git', 'rev-parse', tag])
        if tag_commit == target_commit:
            print(tag)
            return
        # The commits along target branch since the root of the branch that the
        # tag is on
        commit_range = '{}..{}'.format(tag, target_commit)
        commits = backtick(['git', 'log', '--oneline', commit_range])
        if commits == '': # target commit earlier in history than tag
            continue
        distance = len(commits.split('\n'))
        if distance < min_distance:
            closest_tag = tag
            min_distance = distance
        elif distance == min_distance: # tie break
            # maybe this tag is further down the same path as the previous; if
            # so choose this one
            commit_range = '{}..{}'.format(closest_tag, tag)
            commits = backtick(['git', 'log', '--oneline', commit_range])
            if not commits == '': # some history starting from previous
                closest_tag = tag
                min_distance = distance
    print(closest_tag)


if __name__ == '__main__':
    main()
