#!/usr/bin/env python
""" Process .travis.yml and make sh file for testing
"""
from __future__ import print_function

import sys
from os.path import dirname, splitext
import warnings

import argparse # Python 2.6, really?

# pip install pyyaml
import yaml

sys.path.append(dirname(__file__))

from travisparse import get_envs, TravisError, get_yaml_entry

def main():
    parser = argparse.ArgumentParser(
        description='Extract sh script from .travis.yml file')
    parser.add_argument('in_yml', default='.travis.yml', nargs='?',
                        help = 'input travis YAML file '
                        '(default is ".travis.yml")')
    parser.add_argument('--out-sh',
                        help = 'output sh file name '
                        '(default is input name with .sh extension)')
    args = parser.parse_args()
    with open(args.in_yml, 'rt') as fobj:
        travis_dict = yaml.load(fobj)
    out_sh = (splitext(args.in_yml)[0] + '.sh' if args.out_sh is None
              else args.out_sh)
    parts = ['# vars']
    try:
        parts.append(get_envs(travis_dict).strip())
    except TravisError:
        warnings.warn('Could not get travis vars from file')
    parts += ['# install'] + get_yaml_entry(travis_dict, 'install')
    parts += ['# test'] + get_yaml_entry(travis_dict, 'script')
    with open(out_sh, 'wt') as fobj:
        fobj.write('\n'.join(parts) + '\n')
    print('Written ' + out_sh)


if __name__ == '__main__':
    main()
